%%% This file was automatically generated by snmpc_mib_to_hrl version 4.24.2
%%% Date: 11-Feb-2014::08:53:33
-ifndef('EXOMETER-METRICS-MIB').
-define('EXOMETER-METRICS-MIB', true).

%% Oids

-define(exometerMetrics, [1,3,6,1,3,7]).

-define(exometerMetricsMIB, [1,3,6,1,6,3,1]).


%% Range values


%% Default values

-endif.
